name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  repro:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check rust-src
        run: ls -l /home/runner/.rustup/toolchains/*/lib/rustlib/src/rust
        continue-on-error: true
      - name: Check rustup components
        run: rustup component list --installed
      - name: Check rust-src (2)
        run: ls -l /home/runner/.rustup/toolchains/*/lib/rustlib/src/rust
        continue-on-error: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check rust-src (3)
        run: ls -l /home/runner/.rustup/toolchains/*/lib/rustlib/src/rust
        continue-on-error: true
